# Generated by Django 3.2.16 on 2022-12-19 22:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('profesion', models.CharField(blank=True, max_length=50, null=True)),
                ('texto', models.TextField(max_length=280)),
                ('activo', models.BooleanField(default=True)),
                ('publicado', models.DateField(default=datetime.datetime(2022, 12, 19, 22, 32, 33, 764875, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'testimonio',
                'verbose_name_plural': 'testimonios',
                'ordering': ['-publicado'],
            },
        ),
    ]
