# Generated by Django 3.2.16 on 2022-12-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eqiupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('npellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, upload_to='nosotras')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'eqiupos',
                'ordering': ['-nombre'],
            },
        ),
    ]
