# Generated by Django 3.2.16 on 2022-12-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotras', '0002_eqiupo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eqiupo',
            new_name='Equipo',
        ),
    ]
