# Generated by Django 3.2.16 on 2022-12-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotras', '0003_rename_eqiupo_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='npellido',
            new_name='apellido',
        ),
    ]
