# Generated by Django 3.2.16 on 2022-12-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotras', '0004_rename_npellido_equipo_apellido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['-nombre'], 'verbose_name': 'equipo', 'verbose_name_plural': 'equipos'},
        ),
        migrations.AlterModelOptions(
            name='nosotras',
            options={'ordering': ['titulo'], 'verbose_name': 'Nos', 'verbose_name_plural': 'Nosotras'},
        ),
    ]
