# Generated by Django 3.2.16 on 2022-12-15 01:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_alter_noticias_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 1, 43, 59, 340653, tzinfo=utc)),
        ),
    ]
