# Generated by Django 3.2.16 on 2022-12-14 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 21, 18, 55, 723259, tzinfo=utc)),
        ),
    ]
