# Generated by Django 3.2.16 on 2022-12-15 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_alter_actividad_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 1, 23, 12, 150725, tzinfo=utc)),
        ),
    ]
