# Generated by Django 3.2.16 on 2022-12-17 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0014_alter_actividad_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2022, 12, 17, 22, 37, 58, 439367, tzinfo=utc)),
        ),
    ]
