# Generated by Django 4.1.4 on 2022-12-16 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='publicado',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 21, 55, 40, 137430, tzinfo=datetime.timezone.utc)),
        ),
    ]
